import 'package:flutter/material.dart';

var headingTextColor = const Color(0xffffffff);
var primaryTextColor = const Color(0xffffffff);
var scaffoldColor = const Color(0xff26242D);
var accentColor = const Color(0xffBB79E3);
var cardColor = const Color(0xff585173);
var buttonColor = const Color(0xff3C374E);
var buttonTextColor = const Color(0xffffffff);
var alternateButtonColor = const Color(0xff2B283A);
var alternateButtonTextColor = const Color(0xffffffff);
var bottomNavBarItemColor = const Color(0xffA0A4A8);
var textBoxColor = const Color(0xff4B4465);
var lightTextBoxColor = const Color(0xffF5F5F5);
var lightTextBoxTextColor = const Color(0xff818D80);
var textBoxTextColor = const Color(0xffDADADA);
var cardBackgroundColor = const Color(0xff2F2C37);
var eventCardItemTitle = const Color(0xffC0C0C0);
var notificationDateColors = const Color(0xffFFC388);
var dividerColor = const Color(0xffdcc1ff);
var unselectedItemColor = const Color(0xff000000);